mosip/mosip=mosip
mosip/documentation=documentation
mosip/registration=registration
mosip/id-authentication=id-authentication
mosip/inji-wallet=inji-wallet
mosip/pixelpass=pixelpass
mosip/mosip-config=mosip-config
mosip/inji-certify=inji-certify
mosip/mosip-helm=mosip-helm
mosip/inji-config=inji-config
mosip/gist=mosip/gist
mosip/captcha=mosip/captcha
mosip/inji-web=mosip/inji-web
mosip/commons=mosip/commons
mosip/mosip-data=mosip-data
mosip/GovStackBuildingBlockAPI=GovStackBuildingBlockAPI
mosip/abis-testing-kit=abis-testing-kit
mosip/address-standard-unification=address-standard-unification
mosip/admin-services=admin-services
mosip/admin-ui=admin-ui
mosip/android-camera-mds=android-camera-mds
mosip/android-match-sdk=android-match-sdk
mosip/android-registration-client=android-registration-client
mosip/artifactory-ref-impl=artifactory-ref-impl
mosip/audit-manager=audit-manager
mosip/authentication-demo-ui=authentication-demo-ui
mosip/bb-identity=bb-identity
mosip/bio-utils=bio-utils
mosip/biometric-certification-framework=biometric-certification-framework
mosip/biosdk-client=biosdk-client
mosip/biosdk-services=biosdk-services
mosip/biosdk-testing-kit=biosdk-testing-kit
mosip/ble-verifier-sdk=ble-verifier-sdk
mosip/compliance-toolkit-batch-job=compliance-toolkit-batch-job
mosip/compliance-toolkit-testcases=compliance-toolkit-testcases
mosip/converters=converters
mosip/data-archive=data-archive
mosip/demosdk=demosdk
mosip/digital-card-service=digital-card-service
mosip/digital-credential-plugins=digital-credential-plugins
mosip/durian=durian
mosip/esignet=esignet
mosip/esignet-artifactory=esignet-artifactory
mosip/esignet-config=esignet-config
mosip/esignet-infra-cloud=esignet-infra-cloud
mosip/esignet-mock-services=esignet-mock-services
mosip/esignet-plugins=esignet-plugins
mosip/esignet-signup=esignet-signup
mosip/githubmanagement=githubmanagement
mosip/governance=governance
mosip/hackathon=hackathon
mosip/helm-gh-pages=helm-gh-pages
mosip/hsm-ref-impl=hsm-ref-impl
mosip/id-claim-169=id-claim-169
mosip/id-repository=id-repository
mosip/ida-auth-sdk=ida-auth-sdk
mosip/ida-data-seeder=ida-data-seeder
mosip/image-compressor=image-compressor
mosip/imagedecoder=imagedecoder
mosip/infra=infra
mosip/inji-infra-cloud=inji-infra-cloud
mosip/inji-mock-services=inji-mock-services
mosip/inji-openid4vp=inji-openid4vp
mosip/inji-openid4vp-ios-swift=inji-openid4vp-ios-swift
mosip/inji-vc-renderer=inji-vc-renderer
mosip/inji-vc-renderer-ios-swift=inji-vc-renderer-ios-swift
mosip/inji-vci-client=inji-vci-client
mosip/inji-vci-client-ios-swift=inji-vci-client-ios-swift
mosip/inji-verify=inji-verify
mosip/integration=integration
mosip/java-migration-utility=java-migration-utility
mosip/k8s-infra=k8s-infra
mosip/kattu=kattu
mosip/keycloak=keycloak
mosip/keymanager=keymanager
mosip/khazana=khazana
mosip/mds-testing-kit=mds-testing-kit
mosip/migration-utility=migration-utility
mosip/mimoto=mimoto
mosip/mock-smtp-sms=mock-smtp-sms
mosip/mosip=mosip
mosip/mosip-acceptance-tests=mosip-acceptance-tests
mosip/mosip-automation-tests=mosip-automation-tests
mosip/mosip-compliance-toolkit=mosip-compliance-toolkit
mosip/mosip-compliance-toolkit-ui=mosip-compliance-toolkit-ui
mosip/mosip-file-server=mosip-file-server
mosip/mosip-functional-tests=mosip-functional-tests
mosip/mosip-gendermag=mosip-gendermag
mosip/mosip-infra=mosip-infra
mosip/mosip-labs=mosip-labs
mosip/mosip-mobileid-sdk=mosip-mobileid-sdk
mosip/mosip-mock-services=mosip-mock-services
mosip/mosip-onboarding=mosip-onboarding
mosip/mosip-opencrvs=mosip-opencrvs
mosip/mosip-openid-bridge=mosip-openid-bridge
mosip/mosip-ref-impl=mosip-ref-impl
mosip/mosip-sdk=mosip-sdk
mosip/mosip-token-seeder=mosip-token-seeder
mosip/mosip-utilities=mosip-utilities
mosip/nfiq=nfiq
mosip/oidc-demo-portal=oidc-demo-portal
mosip/open-spec=open-spec
mosip/otp-manager=otp-manager
mosip/packet-manager=packet-manager
mosip/partner-management-portal=partner-management-portal
mosip/partner-management-services=partner-management-services
mosip/performance-test-scripts=performance-test-scripts
mosip/pixelpass-ios-swift=pixelpass-ios-swift
mosip/postgres-init=postgres-init
mosip/pre-registration=pre-registration
mosip/pre-registration-ui=pre-registration-ui
mosip/pre-registration-ui-old=pre-registration-ui-old
mosip/print=print
mosip/project-proposals=project-proposals
mosip/registration-client=registration-client
mosip/release-script=release-script
mosip/reporting=reporting
mosip/resident-services=resident-services
mosip/resident-ui=resident-ui
mosip/sbi-capacitor-plugin=sbi-capacitor-plugin
mosip/secure-keystore=secure-keystore
mosip/secure-keystore-ios-swift=secure-keystore-ios-swift
mosip/security-tools=security-tools
mosip/sunbird-telemetry-sdk=sunbird-telemetry-sdk
mosip/templates=templates
mosip/test-management=test-management
mosip/tusd-server=tusd-server
mosip/tuvali=tuvali
mosip/tuvali-ios-swift=tuvali-ios-swift
mosip/vc-verifier=vc-verifier
mosip/websub=websub
